name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with SwiftPM
        run: |
          swift build -c release
          mkdir -p output
          cp -R .build/release/lightroom-template-helper output/lightroom-template-helper.app
          cd output && zip -r lightroom-template.zip lightroom-template-helper.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightroomTemplateApp
          path: output/lightroom-template.zip
  
