name: Build macOS App Bundle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with SwiftPM
        run: |
          swift build -c release

      - name: Create .app bundle and copy resources
        run: |
          mkdir -p output/lightroom-template-helper.app/Contents/MacOS
          cp .build/release/lightroom-template-helper output/lightroom-template-helper.app/Contents/MacOS/

          # Copy template resources
          mkdir -p output/lightroom-template-helper.app/Contents/Resources
          cp -R LightroomTemplates output/lightroom-template-helper.app/Contents/Resources/

          # Create Info.plist
          cat <<EOF > output/lightroom-template-helper.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleExecutable</key>
            <string>lightroom-template-helper</string>
            <key>CFBundleIdentifier</key>
            <string>com.unl.lightroom.template</string>
            <key>CFBundleName</key>
            <string>Lightroom Templates Generator</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>NSHighResolutionCapable</key>
            <true/>
          </dict>
          </plist>
          EOF

      - name: Zip .app
        run: |
          cd output && zip -r lightroom-template.zip lightroom-template-helper.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightroomTemplateApp
          path: output/lightroom-template.zip
