name: Build macOS App Bundle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with SwiftPM
        run: |
          swift build -c release

      - name: Create .app bundle
        run: |
          mkdir -p output/lightroom-template-helper.app/Contents/MacOS
          cp .build/release/lightroom-template-helper output/lightroom-template-helper.app/Contents/MacOS/

          # Add the .command launcher
          cat <<EOF > output/OPEN\ THIS\ FIRST.command
          #!/bin/bash

          cd "\$(dirname "\$0")"

          APP_NAME="lightroom-template-helper.app"
          ZIP_NAME="lightroom-template.zip"

          clear
          echo ""
          echo "🚀 Preparing to launch Lightroom Templates Generator..."
          echo ""

          if [ ! -d "\$APP_NAME" ]; then
            echo "❌ ERROR: \$APP_NAME not found in this folder."
            sleep 5
            exit 1
          fi

          echo "🧹 Removing macOS quarantine flag..."
          xattr -rd com.apple.quarantine "\$APP_NAME"

          echo "📂 Launching the app..."
          open "\$APP_NAME"

          PARENT_DIR="\$(dirname "\$(pwd)")"
          ZIP_PATH="\$PARENT_DIR/\$ZIP_NAME"

          if [ -f "\$ZIP_PATH" ]; then
            echo ""
            read -p "🗑️  Delete the original ZIP file (\$ZIP_NAME)? [y/N]: " DELETE_ZIP
            if [[ "\$DELETE_ZIP" =~ ^[Yy]$ ]]; then
              rm "\$ZIP_PATH"
              echo "🗑️  ZIP file deleted."
            else
              echo "📦 ZIP file kept."
            fi
          fi

          SCRIPT_NAME=\$(basename "\$0")
          echo ""
          read -p "🧼 Delete this launcher script (\$SCRIPT_NAME)? [y/N]: " DELETE_ME
          if [[ "\$DELETE_ME" =~ ^[Yy]$ ]]; then
            rm -- "\$0"
            echo "🧼 Launcher script deleted."
          else
            echo "📂 Launcher script kept."
          fi

          sleep 3
          osascript -e 'tell application "Terminal" to quit'
          exit 0
          EOF

          chmod +x output/OPEN\ THIS\ FIRST.command

          # Create Info.plist
          cat <<EOF > output/lightroom-template-helper.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleExecutable</key>
            <string>lightroom-template-helper</string>
            <key>CFBundleIdentifier</key>
            <string>com.unl.lightroom.template</string>
            <key>CFBundleName</key>
            <string>Lightroom Templates Generator</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>NSHighResolutionCapable</key>
            <true/>
          </dict>
          </plist>
          EOF

      - name: Zip .app
        run: |
          cd output && zip -r lightroom-template.zip lightroom-template-helper.app OPEN\ THIS\ FIRST.command

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightroomTemplateApp
          path: output/lightroom-template.zip
